// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: message_service.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsEventRequest) Reset() {
	*x = WsEventRequest{}
	mi := &file_message_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsEventRequest) ProtoMessage() {}

func (x *WsEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsEventRequest.ProtoReflect.Descriptor instead.
func (*WsEventRequest) Descriptor() ([]byte, []int) {
	return file_message_service_proto_rawDescGZIP(), []int{0}
}

func (x *WsEventRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *WsEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WsEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsEventResponse) Reset() {
	*x = WsEventResponse{}
	mi := &file_message_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsEventResponse) ProtoMessage() {}

func (x *WsEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsEventResponse.ProtoReflect.Descriptor instead.
func (*WsEventResponse) Descriptor() ([]byte, []int) {
	return file_message_service_proto_rawDescGZIP(), []int{1}
}

func (x *WsEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WsEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_message_service_proto protoreflect.FileDescriptor

const file_message_service_proto_rawDesc = "" +
	"\n" +
	"\x15message_service.proto\x12\amessage\"Y\n" +
	"\x0eWsEventRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"A\n" +
	"\x0fWsEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2U\n" +
	"\x10MessageProcessor\x12A\n" +
	"\fProcessEvent\x12\x17.message.WsEventRequest\x1a\x18.message.WsEventResponseB8Z6github.com/bottomhalf/btc-grpc-shared/genproto/messageb\x06proto3"

var (
	file_message_service_proto_rawDescOnce sync.Once
	file_message_service_proto_rawDescData []byte
)

func file_message_service_proto_rawDescGZIP() []byte {
	file_message_service_proto_rawDescOnce.Do(func() {
		file_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_service_proto_rawDesc), len(file_message_service_proto_rawDesc)))
	})
	return file_message_service_proto_rawDescData
}

var file_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_service_proto_goTypes = []any{
	(*WsEventRequest)(nil),  // 0: message.WsEventRequest
	(*WsEventResponse)(nil), // 1: message.WsEventResponse
}
var file_message_service_proto_depIdxs = []int32{
	0, // 0: message.MessageProcessor.ProcessEvent:input_type -> message.WsEventRequest
	1, // 1: message.MessageProcessor.ProcessEvent:output_type -> message.WsEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_service_proto_init() }
func file_message_service_proto_init() {
	if File_message_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_service_proto_rawDesc), len(file_message_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_service_proto_goTypes,
		DependencyIndexes: file_message_service_proto_depIdxs,
		MessageInfos:      file_message_service_proto_msgTypes,
	}.Build()
	File_message_service_proto = out.File
	file_message_service_proto_goTypes = nil
	file_message_service_proto_depIdxs = nil
}
