// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: message_service.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageProcessor_ProcessEvent_FullMethodName = "/message.MessageProcessor/ProcessEvent"
)

// MessageProcessorClient is the client API for MessageProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageProcessorClient interface {
	ProcessEvent(ctx context.Context, in *WsEventRequest, opts ...grpc.CallOption) (*WsEventResponse, error)
}

type messageProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageProcessorClient(cc grpc.ClientConnInterface) MessageProcessorClient {
	return &messageProcessorClient{cc}
}

func (c *messageProcessorClient) ProcessEvent(ctx context.Context, in *WsEventRequest, opts ...grpc.CallOption) (*WsEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WsEventResponse)
	err := c.cc.Invoke(ctx, MessageProcessor_ProcessEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageProcessorServer is the server API for MessageProcessor service.
// All implementations must embed UnimplementedMessageProcessorServer
// for forward compatibility.
type MessageProcessorServer interface {
	ProcessEvent(context.Context, *WsEventRequest) (*WsEventResponse, error)
	mustEmbedUnimplementedMessageProcessorServer()
}

// UnimplementedMessageProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageProcessorServer struct{}

func (UnimplementedMessageProcessorServer) ProcessEvent(context.Context, *WsEventRequest) (*WsEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessEvent not implemented")
}
func (UnimplementedMessageProcessorServer) mustEmbedUnimplementedMessageProcessorServer() {}
func (UnimplementedMessageProcessorServer) testEmbeddedByValue()                          {}

// UnsafeMessageProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageProcessorServer will
// result in compilation errors.
type UnsafeMessageProcessorServer interface {
	mustEmbedUnimplementedMessageProcessorServer()
}

func RegisterMessageProcessorServer(s grpc.ServiceRegistrar, srv MessageProcessorServer) {
	// If the following call panics, it indicates UnimplementedMessageProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageProcessor_ServiceDesc, srv)
}

func _MessageProcessor_ProcessEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WsEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageProcessorServer).ProcessEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageProcessor_ProcessEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageProcessorServer).ProcessEvent(ctx, req.(*WsEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageProcessor_ServiceDesc is the grpc.ServiceDesc for MessageProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageProcessor",
	HandlerType: (*MessageProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessEvent",
			Handler:    _MessageProcessor_ProcessEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_service.proto",
}
